# Data Structures, Functions, Numpy & Pandas

## Section A : Data Structures & Control Structures

#### 1.Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [13]:
my_list = [2,3,4,5,6]
print(my_list)

my_list.append(8)
print("After append:",my_list)

my_list.extend([10,20])
print("After extend:",my_list)

my_list.insert(3, 9)
print("After insert:",my_list)

my_list.remove(5)
print("After remove:",my_list)

pop_value = my_list.pop(3)
print("After pop:",pop_value)

index_value = my_list.index(6)
print("After index:",index_value)

count_value = my_list.count(2)
print("After count:",count_value)

my_list.sort()
print("After sort:",my_list)

my_list.reverse()
print("After reverse:",my_list)

my_list.clear()
print("After clear:",my_list)

[2, 3, 4, 5, 6]
After append: [2, 3, 4, 5, 6, 8]
After extend: [2, 3, 4, 5, 6, 8, 10, 20]
After insert: [2, 3, 4, 9, 5, 6, 8, 10, 20]
After remove: [2, 3, 4, 9, 6, 8, 10, 20]
After pop: 9
After index: 3
After count: 1
After sort: [2, 3, 4, 6, 8, 10, 20]
After reverse: [20, 10, 8, 6, 4, 3, 2]
After clear: []


#### 2.Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [15]:
students = ("Saloni","Sayali","Samrudhi")
print(students)

students[1] = "Anamika"

print("Updated tuple:",students)

('Saloni', 'Sayali', 'Samrudhi')


TypeError: 'tuple' object does not support item assignment

###### A Tuple is immutable, which means it cannot be changed after it is created
###### You cannot add, remove, or modify elements in a tuple.
###### When you try to change students[1], Python gives an error because it does not allow modification.

#### 3.Create a set of integers with some duplicate values. Print the set and explain the output

In [16]:
numbers = {1,2,3,4,2,4}

print("Set:", numbers)

Set: {1, 2, 3, 4}


###### A set in python not allow duplicate values.
###### Even though we wrote 2 and 4 twice, they appear only once in the output.
###### Sets automatically remove duplicates.
###### Sets are also unordered, so the elements may not appear in the same order every time.

#### 4.Create a dictionary with the keys: 'name', 'age', and 'city'.Update the age and add a new key 'email'. Print the final dictionary.

In [20]:
person = {
    "name": "Pragati",
    "age": "19",
    "city": "Pune"
}
print("Dictionary:",person)

person["age"] = 20

person["email"] = "pragati@example.com"

print("Updated Dictionary:",person)

Dictionary: {'name': 'Pragati', 'age': '19', 'city': 'Pune'}
Updated Dictionary: {'name': 'Pragati', 'age': 20, 'city': 'Pune', 'email': 'pragati@example.com'}


#### 5.Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [2]:
age = 20

if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote.")


You are eligible to vote.


#### 6.	Given a 'marks' variable, print the grade:
#### - 90 and above: 'A'
#### - 75–89: 'B'
#### - 50–74: 'C'
#### - Below 50: 'Fail'

In [3]:
marks = 80

if marks >= 90:
    print("Grade A")
elif marks >= 75:
    print("Grade B")
elif marks >= 50:
    print("Grade C")
else:
    print("Fail")

Grade B


#### 7.Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [5]:
num = 4

if num > 0:
    print("Number is positive")

    if num % 2 == 0:
        print("It is also even")
    else:
        print("It is odd")

elif num == 0:
    print("Number is zero")

else:
    print("Number is negative")

Number is positive
It is also even


## Section B : Numpy

#### 8.Create:
#### - A scalar using np.array(5)
#### - A 1D array with values 1 to 5
#### - A 2D array (2x3) with values from 10 to 60 in steps of 10

In [7]:
import numpy as np

scalar = np.array(5)
print("Scalar:")
print(scalar)

arr_1d = np.array([1, 2, 3, 4, 5])
print("\n1D Array:")
print(arr_1d)

arr_2d = np.array([[10, 20, 30],
                  [40, 50, 60]])
print("\n2D Array:")
print(arr_2d)

Scalar:
5

1D Array:
[1 2 3 4 5]

2D Array:
[[10 20 30]
 [40 50 60]]


#### 9.Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [8]:
import numpy as np

arr = np.random.randint(0, 100, (4, 4))
print(arr)

[[88 28 72 42]
 [32 39 85 98]
 [80 56 41 51]
 [60 42 58 10]]


#### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [10]:
import numpy as np
import pandas as pd

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

df = pd.DataFrame(arr, columns=['A', 'B', 'C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


## Section C: Exploring Pandas

#### 11.Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
####  - Use .info(), .describe()
####  - Select 'Name' and 'City' columns
####  - Drop 'City' column
####  - Fill any missing values in 'Salary' column with the mean
####  - Remove any duplicate rows


In [48]:
import numpy as np
import pandas as pd

data = {
    'Name': ['Riya', 'Rasika', 'Shreya', 'Saloni', 'Payal', 'Shruti', 'Rutuja', 'Arati', 'Anamika', 'Samrudhi'],
    'Age': [26, 22, 23, 23, 23, 24, 24, 24, 24, 24,],
    'City': ['Mumbai', 'Pune', 'Delhi', 'Chennai', 'Pune', 'Mumbai', 'Bengaluru', 'Delhi', 'Chennai', 'Pune'],
    'Salary': [np.nan, 50000, 45000, 35000, 42000, 21000, 55000, 34000, np.nan, 52000]
}

df = pd.DataFrame(data)

df.info()
df.describe()

print(df[['Name', 'City']])
df = df.drop('City', axis=1)

df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

df = df.drop_duplicates()

print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
       Name       City
0      Riya     Mumbai
1    Rasika       Pune
2    Shreya      Delhi
3    Saloni    Chennai
4     Payal       Pune
5    Shruti     Mumbai
6    Rutuja  Bengaluru
7     Arati      Delhi
8   Anamika    Chennai
9  Samrudhi       Pune
       Name  Age   Salary
0      Riya   26  41750.0
1    Rasika   22  50000.0
2    Shreya   23  45000.0
3    Saloni   23  35000.0
4     Payal   23  42000.0
5    Shruti   24  21000.0
6    Rutuja   24  55000.0
7     Arati   24  34000.0
8   Anamika   24  41750.0
9  Samrudhi   24  52000.0
